#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --

MODIFIED_FILES=$(git diff --name-only HEAD~)

# Check csscomb

CSSCOMB=$(which csscomb 2> /dev/null)
if [[ -z "$CSSCOMB" ]]; then
        cat <<\EOF
Error: csscomb is not installed.

With yarn:

        yarn global add csscomb

With NPM:
        npm install -g csscomb

Aborting commit.
EOF
        exit 1
fi

# there might be multiple subdirectories with multiple csscomb configurations
for csscomb_config in $(find . -name '.csscomb.json'); do
        csscomb --config "$csscomb_config" --lint "$MODIFIED_FILES"
        if [[ $? -ne 0 ]]; then
                echo "Error formatting using csscomb, aborting commit."
                exit 1
        fi
done

# Check editorconfig

EDITORCONFIG_TOOLS=$(which editorconfig-tools 2> /dev/null)
if [[ -z "$EDITORCONFIG_TOOLS" ]]; then
        cat <<\EOF
Error: editorconfig-tools is not installed.

With yarn:

        yarn global add editorconfig-tools

With NPM:
        npm install -g editorconfig-tools

Aborting commit.
EOF
        exit 1
fi

for file in "$MODIFIED_FILES"; do
        editorconfig-tools check "$file"

        if [[ $? -ne 0 ]]; then
                cat <<\EOF
There are misformatted files, please fix them. Remember you can do
this by just using the following command:

        editorconfig-tools fix path/to/my/files/**/*

Aborting commit.
EOF
                exit 1
        fi
done
