#!/bin/sh

MODIFIED_FILES=$(git diff --name-only HEAD~ | grep -v '.svg' | grep -v '.png' | grep -v '.jpg' | grep -v '.snap')

# Check csscomb

CSSCOMB=$(which csscomb 2> /dev/null)
if [[ -z "$CSSCOMB" ]]; then
        cat <<\EOF
Error: csscomb is not installed.

With yarn:

        yarn global add csscomb

With NPM:
        npm install -g csscomb

Aborting commit.
EOF
        exit 1
fi

# there might be multiple subdirectories with multiple csscomb configurations
for csscomb_config in $(find . -name '.csscomb.json'); do
        csscomb --config "$csscomb_config" --lint "$MODIFIED_FILES"
        if [[ $? -ne 0 ]]; then
                echo "Error formatting using csscomb, aborting commit."
                exit 1
        fi
done

# Check editorconfig

EDITORCONFIG_TOOLS=$(which editorconfig-tools 2> /dev/null)
if [[ -z "$EDITORCONFIG_TOOLS" ]]; then
        cat <<\EOF
Error: editorconfig-tools is not installed.

With yarn:

        yarn global add editorconfig-tools

With NPM:
        npm install -g editorconfig-tools

Aborting commit.
EOF
        exit 1
fi

for file in "$MODIFIED_FILES"; do
        editorconfig-tools check "$file"

        if [[ $? -ne 0 ]]; then
                cat <<\EOF
There are misformatted files, please fix them. Remember you can do
this by just using the following command:

        editorconfig-tools fix path/to/my/files/**/*

Aborting commit.
EOF
                exit 1
        fi
done
